use_frameworks!

platform :ios, '8.0'

target 'Batch-Firebase-Dispatcher_Example' do
  pod 'Batch-Firebase-Dispatcher', :path => '../'

  target 'Batch-Firebase-Dispatcher_Tests' do
    inherit! :search_paths
    
    pod 'OCMock'
  end
end
